language: python
python:
  - "3.6"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  # Useful for debugging any issues with conda
  - conda info -a
  - pip install -e .
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest numpy scipy
  - source activate test-environment

# command to install dependencies
# install: ""

# command to run tests
script: pytest
